theme: jekyll-theme-minimal
markdown: kramdown
auto_ids: true
logo: preview.jpg
show_downloads: True
google_analytics: False
steamurl: https://steamcommunity.com/sharedfiles/filedetails/?id=2448492759
github:
  zip_url: /The-Modpack/zipball