theme: jekyll-theme-minimal
markdown: kramdown
auto_ids: true
logo: preview.jpg
show_downloads: True
google_analytics: False
github:
  zip_url: {{ site.github.repository_url }}/zipball/master
  steam_url: https://steamcommunity.com/sharedfiles/filedetails/?id=2448492759